import { useState, useEffect, useMemo } from 'react';
import {
  Box,
  Typography,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
  Paper,
  Chip,
  Tooltip,
  IconButton,
  Button,
  TextField,
  InputAdornment,
  Stack,
  MenuItem,
  Select,
} from '@mui/material';
import FolderIcon from '@mui/icons-material/Folder';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import DeleteIcon from '@mui/icons-material/Delete';
import FilterListIcon from '@mui/icons-material/FilterList';
import CloseIcon from '@mui/icons-material/Close';
import SearchIcon from '@mui/icons-material/Search';
import DataTable from '../../components/DataTable';
import type { AppDocument } from '../../types';
import {
  Group as PanelGroup,
  Panel,
  Separator as PanelResizeHandle,
  useDefaultLayout,
} from 'react-resizable-panels';
import { subtleScrollSx } from '../../styles';

interface DocumentsListProps {
  documents: AppDocument[];
  handleOpen: (doc: AppDocument) => void;
  handleDeleteClick: (id: string) => void;
}

function StyledResizeHandle({ ariaLabel }: { ariaLabel: string }) {
  return (
    <PanelResizeHandle aria-label={ariaLabel} style={{ width: 16, position: 'relative' }}>
      <Box
        sx={{
          position: 'absolute',
          inset: 0,
          margin: '0 auto',
          width: 2,
          bgcolor: 'divider',
          borderRadius: 1,
          transition: 'background-color 120ms ease',
          '[data-resize-handle-active] &, &:hover': {
            bgcolor: 'primary.main',
            width: 3,
          },
        }}
      />
    </PanelResizeHandle>
  );
}

function PanelScroll({ children }: { children: React.ReactNode }) {
  return (
    <Box sx={{ height: '100%', overflow: 'auto', ...subtleScrollSx }}>
      {children}
    </Box>
  );
}

export function DocumentsList({ documents, handleOpen, handleDeleteClick }: DocumentsListProps) {
  const [searchInput, setSearchInput] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [filtersOpen, setFiltersOpen] = useState(false);

  const [sourceFilter, setSourceFilter] = useState('all');
  const [checklistFilter, setChecklistFilter] = useState('all');

  const panelIds = useMemo(() => [
    ...(filtersOpen ? ['filters'] : []),
    'table'
  ], [filtersOpen]);
  const { defaultLayout, onLayoutChanged } = useDefaultLayout({
    id: `documents-layout-v3-${panelIds.join('-')}`,
    panelIds,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  });

  useEffect(() => {
    const timer = setTimeout(() => {
      setSearchQuery(searchInput);
    }, 300);
    return () => clearTimeout(timer);
  }, [searchInput]);

  const filteredDocuments = useMemo(() => {
    return documents.filter((doc) => {
      const matchesSearch = !searchQuery || doc.name.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesSource = sourceFilter === 'all' || doc.source === sourceFilter;
      const matchesChecklist =
        checklistFilter === 'all' ||
        (checklistFilter === 'checklist' && Boolean(doc.associatedChecklistId)) ||
        (checklistFilter === 'none' && !doc.associatedChecklistId);

      return matchesSearch && matchesSource && matchesChecklist;
    });
  }, [documents, searchQuery, sourceFilter, checklistFilter]);

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0, gap: 2.5 }}>
      <Box>
        <Typography variant="h4" fontWeight="800" sx={{ mb: 1, display: 'flex', alignItems: 'center', gap: 1.5 }}>
          Documents
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Track and manage documents generated by the AI or uploaded for taxes.
        </Typography>
      </Box>

      {/* Search & Filter bar */}
      <Stack direction="row" spacing={2} alignItems="center">
        <Button
          variant={filtersOpen ? 'contained' : 'outlined'}
          size="small"
          startIcon={<FilterListIcon />}
          onClick={() => setFiltersOpen(!filtersOpen)}
          sx={{ textTransform: 'none', borderRadius: (theme) => `${theme.shape.borderRadius}px`, height: 40 }}
        >
          Filters {(sourceFilter !== 'all' || checklistFilter !== 'all') ? '•' : ''}
        </Button>
        <Box sx={{ flex: 1, maxWidth: 400 }}>
          <TextField
            placeholder="Search documents..."
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            size="small"
            fullWidth
            slotProps={{
              input: {
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon fontSize="small" color="action" />
                  </InputAdornment>
                ),
                endAdornment: searchInput && (
                  <InputAdornment position="end">
                    <IconButton size="small" onClick={() => { setSearchInput(''); setSearchQuery(''); }}>
                      <CloseIcon fontSize="small" />
                    </IconButton>
                  </InputAdornment>
                )
              }
            }}
          />
        </Box>
      </Stack>

      {/* Main Layout Area */}
      <Box sx={{ display: 'flex', flexDirection: 'column', flexGrow: 1, minHeight: 0 }}>
        <PanelGroup
          key={`documents-${filtersOpen ? 'open' : 'closed'}`}
          orientation="horizontal"
          defaultLayout={defaultLayout}
          onLayoutChanged={onLayoutChanged}
          style={{ height: '100%' }}
        >
          {filtersOpen && (
            <Panel id="filters" defaultSize="25%" minSize="20%" maxSize="40%">
              <PanelScroll>
                <Stack spacing={3} sx={{ pr: 1, py: 1 }}>
                  <Typography variant="subtitle1" fontWeight={600}>
                    Advanced Filters
                  </Typography>

                  <Box>
                    <Typography variant="body2" color="text.secondary" gutterBottom>
                      Document Source
                    </Typography>
                    <Select
                      fullWidth
                      size="small"
                      value={sourceFilter}
                      onChange={(e) => setSourceFilter(e.target.value)}
                    >
                      <MenuItem value="all">All Sources</MenuItem>
                      <MenuItem value="generated">AI Generated</MenuItem>
                      <MenuItem value="uploaded">Uploaded</MenuItem>
                    </Select>
                  </Box>

                  <Box>
                    <Typography variant="body2" color="text.secondary" gutterBottom>
                      Checklist Association
                    </Typography>
                    <Select
                      fullWidth
                      size="small"
                      value={checklistFilter}
                      onChange={(e) => setChecklistFilter(e.target.value)}
                    >
                      <MenuItem value="all">All Associations</MenuItem>
                      <MenuItem value="checklist">Has Checklist Item</MenuItem>
                      <MenuItem value="none">No Checklist Item</MenuItem>
                    </Select>
                  </Box>

                  <Button
                    variant="outlined"
                    fullWidth
                    onClick={() => {
                      setSourceFilter('all');
                      setChecklistFilter('all');
                      setSearchQuery('');
                      setSearchInput('');
                    }}
                  >
                    Clear All Filters
                  </Button>
                </Stack>
              </PanelScroll>
            </Panel>
          )}

          {filtersOpen && <StyledResizeHandle ariaLabel="Resize filters / table" />}

          <Panel id="table" defaultSize="75%" minSize="30%">
            <Box
              sx={{
                position: 'relative',
                flexGrow: 1,
                minHeight: 0,
                display: 'flex',
                flexDirection: 'column',
                height: '100%',
                pl: filtersOpen ? 1 : 0,
              }}
            >
              {filteredDocuments.length > 0 ? (
                <DataTable stickyHeader size="small">
                  <TableHead>
                    <TableRow>
                      <TableCell sx={{ pl: 3 }}>Name</TableCell>
                      <TableCell>Date Created</TableCell>
                      <TableCell>Source</TableCell>
                      <TableCell>Tax Checklist Item</TableCell>
                      <TableCell>Local Path</TableCell>
                      <TableCell align="right" sx={{ pr: 3 }}>Actions</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {filteredDocuments.map((doc: AppDocument) => (
                      <TableRow key={doc.id} hover sx={{ '&:last-child td': { borderBottom: 0 } }}>
                        <TableCell sx={{ pl: 3 }}>
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                            <Typography
                              variant="body2"
                              fontWeight="600"
                              color="primary.main"
                              onClick={() => handleOpen(doc)}
                              sx={{ cursor: 'pointer', '&:hover': { textDecoration: 'underline' } }}
                            >
                              {doc.name}
                            </Typography>
                          </Box>
                        </TableCell>
                        <TableCell sx={{ color: 'text.secondary' }}>
                          {new Date(doc.createdAt).toLocaleString()}
                        </TableCell>
                        <TableCell>
                          <Chip
                            label={doc.source === 'generated' ? 'AI' : 'Uploaded'}
                            size="small"
                            color={doc.source === 'generated' ? 'secondary' : 'default'}
                            variant={doc.source === 'generated' ? 'filled' : 'outlined'}
                            sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}
                          />
                        </TableCell>
                        <TableCell>
                          {doc.associatedChecklistId ? (
                            <Chip
                              label={doc.associatedChecklistId === 'business_pnl' ? 'Business P&L' : doc.associatedChecklistId}
                              size="small"
                              color="success"
                              variant="outlined"
                              sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}
                            />
                          ) : (
                            <Typography variant="caption" color="text.disabled">—</Typography>
                          )}
                        </TableCell>
                        <TableCell sx={{ color: 'text.secondary', fontFamily: 'monospace', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={doc.path}>
                          {doc.path}
                        </TableCell>
                        <TableCell align="right" sx={{ pr: 3 }}>
                          <Box sx={{ display: 'flex', gap: 1, justifyContent: 'flex-end' }}>
                            <Tooltip title="Open File">
                              <IconButton size="small" onClick={() => handleOpen(doc)} sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}>
                                <OpenInNewIcon fontSize="small" />
                              </IconButton>
                            </Tooltip>
                            <Tooltip title="Remove record">
                              <IconButton size="small" color="error" onClick={() => handleDeleteClick(doc.id)} sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}>
                                <DeleteIcon fontSize="small" />
                              </IconButton>
                            </Tooltip>
                          </Box>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </DataTable>
              ) : (
                <Paper
                  elevation={0}
                  sx={{
                    p: 6,
                    textAlign: 'center',
                    borderRadius: (theme) => `${theme.shape.borderRadius}px`,
                    border: '1px dashed',
                    borderColor: 'divider',
                    bgcolor: 'transparent'
                  }}
                >
                  <FolderIcon sx={{ fontSize: 64, color: 'text.disabled', mb: 2 }} />
                  <Typography variant="h6" color="text.secondary" fontWeight="600" gutterBottom>
                    {documents.length > 0 ? "No Matching Documents" : "No Documents Yet"}
                  </Typography>
                  <Typography variant="body2" color="text.disabled">
                    {documents.length > 0 ? "Try adjusting your search or filters." : "Ask the AI Copilot to generate a report or upload a document in the Tax Center."}
                  </Typography>
                </Paper>
              )}
            </Box>
          </Panel>
        </PanelGroup>
      </Box>
    </Box>
  );
}
