import {
  Box,
  Typography,
  TableContainer,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
  Paper,
  Chip,
  Tooltip,
  IconButton
} from '@mui/material';
import FolderIcon from '@mui/icons-material/Folder';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import DeleteIcon from '@mui/icons-material/Delete';
import type { AppDocument } from '../../types';

interface DocumentsListProps {
  documents: AppDocument[];
  handleOpen: (doc: AppDocument) => void;
  handleDeleteClick: (id: string) => void;
}

export function DocumentsList({ documents, handleOpen, handleDeleteClick }: DocumentsListProps) {
  return (
    <Box>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" fontWeight="800" sx={{ mb: 1, display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <FolderIcon fontSize="large" color="primary" />
          Documents
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Track and manage documents generated by the AI or uploaded for taxes.
        </Typography>
      </Box>

      {documents.length > 0 ? (
        <TableContainer
          component={Paper}
          variant="outlined"
          sx={{
            borderRadius: (theme) => `${theme.shape.borderRadius}px`,
            overflow: 'hidden',
            borderColor: 'divider',
            boxShadow: '0 2px 8px rgba(0,0,0,0.02)',
          }}
        >
          <Table sx={{ minWidth: 650 }}>
            <TableHead>
              <TableRow>
                <TableCell sx={{ pl: 3 }}>Name</TableCell>
                <TableCell>Date Created</TableCell>
                <TableCell>Source</TableCell>
                <TableCell>Tax Checklist Item</TableCell>
                <TableCell>Local Path</TableCell>
                <TableCell align="right" sx={{ pr: 3 }}>Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {documents.map((doc: AppDocument) => (
                <TableRow key={doc.id} hover sx={{ '&:last-child td': { borderBottom: 0 } }}>
                  <TableCell sx={{ pl: 3 }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                      <Typography variant="body2" fontWeight="600" color="text.primary">
                        {doc.name}
                      </Typography>
                    </Box>
                  </TableCell>
                  <TableCell sx={{ color: 'text.secondary' }}>
                    {new Date(doc.createdAt).toLocaleString()}
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={doc.source === 'generated' ? 'AI' : 'Uploaded'}
                      size="small"
                      color={doc.source === 'generated' ? 'secondary' : 'default'}
                      variant={doc.source === 'generated' ? 'filled' : 'outlined'}
                      sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}
                    />
                  </TableCell>
                  <TableCell>
                    {doc.associatedChecklistId ? (
                      <Chip
                        label={doc.associatedChecklistId === 'business_pnl' ? 'Business P&L' : doc.associatedChecklistId}
                        size="small"
                        color="success"
                        variant="outlined"
                        sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}
                      />
                    ) : (
                      <Typography variant="caption" color="text.disabled">—</Typography>
                    )}
                  </TableCell>
                  <TableCell sx={{ color: 'text.secondary', fontFamily: 'monospace', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={doc.path}>
                    {doc.path}
                  </TableCell>
                  <TableCell align="right" sx={{ pr: 3 }}>
                    <Box sx={{ display: 'flex', gap: 1, justifyContent: 'flex-end' }}>
                      <Tooltip title="Open File">
                        <IconButton size="small" onClick={() => handleOpen(doc)} sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}>
                          <OpenInNewIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title="Remove record">
                        <IconButton size="small" color="error" onClick={() => handleDeleteClick(doc.id)} sx={{ borderRadius: (theme) => `${theme.shape.borderRadius}px` }}>
                          <DeleteIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      ) : (
        <Paper
          elevation={0}
          sx={{
            p: 6,
            textAlign: 'center',
            borderRadius: (theme) => `${theme.shape.borderRadius}px`,
            border: '1px dashed',
            borderColor: 'divider',
            bgcolor: 'transparent'
          }}
        >
          <FolderIcon sx={{ fontSize: 64, color: 'text.disabled', mb: 2 }} />
          <Typography variant="h6" color="text.secondary" fontWeight="600" gutterBottom>
            No Documents Yet
          </Typography>
          <Typography variant="body2" color="text.disabled">
            Ask the AI Copilot to generate a report or upload a document in the Tax Center.
          </Typography>
        </Paper>
      )}
    </Box>
  );
}
