import { db } from "../db/drizzle";
import * as schema from "../db/schema";
import { eq } from 'drizzle-orm';
import { useArtifacts } from '../hooks/queries';

import {
  Box,
  Typography,
  Card,
  CardContent,
  CardActions,
  Button,
  Chip,
} from '@mui/material';
import { useChatStore } from '../chatStore';

export default function ArtifactsLibrary() {
  const { data: artifacts } = useArtifacts();
  const setActiveArtifact = useChatStore((s) => s.setActiveArtifact);

  if (!artifacts) {
    return <Typography>Loading...</Typography>;
  }

  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        Artifacts Library
      </Typography>
      <Typography variant="body1" color="text.secondary" gutterBottom>
        Manage and view code snippets, skills, and documents generated by your local AI.
      </Typography>
      <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: 3, mt: 2 }}>
        {artifacts.length === 0 ? (
          <Box sx={{ gridColumn: '1 / -1' }}>
            <Typography variant="body2" color="text.secondary">
              No artifacts found. Ask the AI to create something!
            </Typography>
          </Box>
        ) : (
          artifacts.map((art) => (
            <Box key={art.id}>
              <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                <CardContent sx={{ flexGrow: 1 }}>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                    <Typography variant="subtitle1" fontWeight={600}>
                      {art.title}
                    </Typography>
                    <Chip label={art.type} size="small" color={art.type === 'skill' ? 'primary' : 'default'} />
                  </Box>
                  <Typography variant="body2" color="text.secondary" sx={{ display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                    {art.explanation || art.content}
                  </Typography>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 2 }}>
                    Updated: {new Date(art.updatedAt).toLocaleString()}
                  </Typography>
                </CardContent>
                <CardActions>
                  <Button 
                    size="small" 
                    onClick={() => {
                      setActiveArtifact(art);
                    }}
                  >
                    View
                  </Button>
                  <Button 
                    size="small" 
                    color="error"
                    onClick={async () => {
                      await db.delete(schema.artifacts).where(eq(schema.artifacts.id, art.id));
                    }}
                  >
                    Delete
                  </Button>
                </CardActions>
              </Card>
            </Box>
          ))
        )}
      </Box>
    </Box>
  );
}
