import {
  Box,
  Typography,
  Grid,
  Card,
  CardActionArea,
  CardContent,
  IconButton,
  Stack,
  alpha,
  useTheme,
} from '@mui/material';
import DeleteIcon from '@mui/icons-material/Delete';
import PsychologyIcon from '@mui/icons-material/Psychology';
import ArticleIcon from '@mui/icons-material/Article';
import GridOnIcon from '@mui/icons-material/GridOn';
import { useArtifacts } from '../hooks/queries';
import { useDeleteArtifact } from '../hooks/mutations';
import { format } from 'date-fns';
import { useNavigate } from 'react-router-dom';
import { confirmDialog } from '../utils/confirmDialog';
import { useFilters } from '../store';
import { useEffect } from 'react';

export default function Artifacts() {
  const theme = useTheme();
  const navigate = useNavigate();
  const { data: artifacts = [], isLoading } = useArtifacts();
  const deleteArtifact = useDeleteArtifact();
  const setLastViewedArtifactsAt = useFilters((s) => s.setLastViewedArtifactsAt);

  useEffect(() => {
    // Update the last viewed timestamp so the new artifacts badge gets cleared
    setLastViewedArtifactsAt(new Date().toISOString());
    return () => {
      setLastViewedArtifactsAt(new Date().toISOString());
    };
  }, [setLastViewedArtifactsAt]);

  const sortedArtifacts = [...artifacts].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());

  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (await confirmDialog('Are you sure you want to delete this artifact?', 'Confirm Delete')) {
      deleteArtifact.mutate(id);
    }
  };



  const getLabelForType = (type: string) => {
    switch (type) {
      case 'skill': return 'Capability';
      case 'spreadsheet': return 'Spreadsheet';
      case 'pdf': return 'PDF Document';
      case 'markdown': return 'Document';
      default: return 'Artifact';
    }
  };

  return (
    <Box sx={{ 
      pb: 6, 
      height: '100%', 
      overflowY: 'auto',
      mr: { xs: -1.5, sm: -3 },
      pr: { xs: 1.5, sm: 4 }
    }}>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" sx={{ fontWeight: 700, mb: 1 }}>
          Artifacts Gallery
        </Typography>
        <Typography variant="body1" color="text.secondary">
          View and manage all files, spreadsheets, and AI capabilities.
        </Typography>
      </Box>

      {isLoading ? null : sortedArtifacts.length === 0 ? (
        <Box sx={{ textAlign: 'center', py: 10 }}>
          <ArticleIcon sx={{ fontSize: 64, color: 'text.disabled', mb: 2 }} />
          <Typography variant="h6" color="text.primary" sx={{ mb: 1 }}>
            No artifacts yet
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Artifacts generated by the AI or uploaded by you will appear here.
          </Typography>
        </Box>
      ) : (
        <Grid container spacing={3} mt={1}>
          {sortedArtifacts.map((art) => (
            <Grid size={{ xs: 12, sm: 6, md: 4, lg: 3 }} key={art.id}>
              <Card
                variant="outlined"
                sx={{
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  transition: 'all 0.2s',
                  '&:hover': {
                    borderColor: 'primary.main',
                    boxShadow: `0 4px 12px ${alpha(theme.palette.primary.main, 0.1)}`,
                    transform: 'translateY(-2px)'
                  }
                }}
              >
                <Box
                  onClick={() => navigate(`/artifacts/${art.id}`)}
                  sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', p: 3, cursor: 'pointer' }}
                >
                  <Stack direction="row" justifyContent="flex-end" width="100%" mb={2}>
                    <IconButton 
                      size="small" 
                      color="error" 
                      onClick={(e) => handleDelete(e, art.id)}
                      onMouseDown={(e) => e.stopPropagation()}
                      sx={{ 
                        opacity: 0, 
                        transition: 'opacity 0.2s',
                        '.MuiCard-root:hover &': { opacity: 1 } 
                      }}
                    >
                      <DeleteIcon fontSize="small" />
                    </IconButton>
                  </Stack>
                  
                  <CardContent sx={{ p: 0, width: '100%' }}>
                    <Typography 
                      variant="h6" 
                      component="div" 
                      sx={{ 
                        fontSize: 16, 
                        fontWeight: 600, 
                        mb: 0.5,
                        display: '-webkit-box',
                        WebkitLineClamp: 2,
                        WebkitBoxOrient: 'vertical',
                        overflow: 'hidden'
                      }}
                    >
                      {art.title}
                    </Typography>
                    {art.summary && (
                      <Typography 
                        variant="body2" 
                        color="text.secondary" 
                        sx={{ 
                          mb: 1,
                          fontSize: 12,
                          display: '-webkit-box',
                          WebkitLineClamp: 3,
                          WebkitBoxOrient: 'vertical',
                          overflow: 'hidden'
                        }}
                      >
                        {art.summary}
                      </Typography>
                    )}
                    <Typography variant="body2" color="text.secondary" sx={{ textTransform: 'uppercase', fontSize: 10, letterSpacing: 0.5, fontWeight: 600, mb: 1 }}>
                      {getLabelForType(art.type)}
                    </Typography>
                    <Typography variant="caption" color="text.disabled" sx={{ display: 'block' }}>
                      Updated {format(new Date(art.updatedAt), 'MMM d, yyyy h:mm a')}
                    </Typography>
                  </CardContent>
                </Box>
              </Card>
            </Grid>
          ))}
        </Grid>
      )}
    </Box>
  );
}
