import { db } from "../db/drizzle";
import * as schema from "../db/schema";
import { eq } from 'drizzle-orm';
import { useState } from 'react';
import {
  Box,
  Typography,
  IconButton,
  Button,
  Paper,
  Stack,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import ArticleIcon from '@mui/icons-material/Article';
import PsychologyIcon from '@mui/icons-material/Psychology';
import CheckIcon from '@mui/icons-material/Check';
import SaveIcon from '@mui/icons-material/Save';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import GridOnIcon from '@mui/icons-material/GridOn';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import FullscreenIcon from '@mui/icons-material/Fullscreen';
import FullscreenExitIcon from '@mui/icons-material/FullscreenExit';
import { useNavigate } from 'react-router-dom';
import { useChatStore } from '../chatStore';
import { useShallow } from 'zustand/react/shallow';
import { useSettings } from '../hooks/queries';

import type { AgentSkill } from '../types';
import SimpleMarkdown from './SimpleMarkdown';

export default function ArtifactViewer() {
  const { activeArtifact, setActiveArtifact } = useChatStore(useShallow((s) => ({
    activeArtifact: s.activeArtifact,
    setActiveArtifact: s.setActiveArtifact,
  })));
  const navigate = useNavigate();
  const { data: settings = [] } = useSettings();
  const activeSkills = settings.find(s => s.key === 'app:agentSkills')?.value as AgentSkill[] || [];
  const [copied, setCopied] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);

  const [prevArtifact, setPrevArtifact] = useState(activeArtifact);
  if (activeArtifact !== prevArtifact) {
    setPrevArtifact(activeArtifact);
    setIsFullscreen(false);
  }

  if (!activeArtifact) return null;

  const isSkill = activeArtifact.type === 'skill';
  const isSpreadsheet = activeArtifact.type === 'spreadsheet';
  const isSaved = isSkill && activeSkills.some(s => s.name === activeArtifact.title);

  const parseSpreadsheet = (content: string): { headers: string[]; rows: string[][] } | null => {
    try {
      const parsed = JSON.parse(content);
      if (parsed && Array.isArray(parsed.headers) && Array.isArray(parsed.rows)) {
        return parsed;
      }
    } catch {
      // ignore JSON parse error, fall back to CSV
    }

    // CSV fallback parsing
    const lines = content.split('\n').map(line => line.trim()).filter(Boolean);
    if (lines.length > 0) {
      const headers = lines[0].split(',').map(h => h.trim().replace(/^["']|["']$/g, ''));
      const rows = lines.slice(1).map(line => line.split(',').map(cell => cell.trim().replace(/^["']|["']$/g, '')));
      return { headers, rows };
    }

    return null;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(activeArtifact.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadCSV = () => {
    const data = parseSpreadsheet(activeArtifact.content);
    if (!data) return;
    const csvContent = [
      data.headers.join(','),
      ...data.rows.map(r => r.join(','))
    ].join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `${activeArtifact.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleSave = async () => {
    const setting = await (await db.select().from(schema.settings).where(eq(schema.settings.key, 'app:agentSkills')))[0];
    const currentSkills = (setting?.value as AgentSkill[]) || [];
    
    // Check if already exists by name
    const existingIndex = currentSkills.findIndex(s => s.name === activeArtifact.title);
    let updated: AgentSkill[];
    if (existingIndex >= 0) {
      updated = [...currentSkills];
      updated[existingIndex] = {
        ...currentSkills[existingIndex],
        systemPromptExtension: activeArtifact.content,
      };
    } else {
      updated = [
        ...currentSkills,
        {
          id: `custom:${Date.now()}`,
          name: activeArtifact.title,
          description: activeArtifact.explanation || 'Custom capability generated by AI.',
          systemPromptExtension: activeArtifact.content,
          enabled: true,
          isBuiltIn: false
        }
      ];
    }
    await db.insert(schema.settings).values({ key: 'app:agentSkills', value: updated })
      .onConflictDoUpdate({ target: schema.settings.key, set: { value: updated } });
  };

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        bgcolor: 'background.default',
        ...(isFullscreen && {
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100vw',
          height: '100vh',
          zIndex: 1300,
          boxShadow: '0 8px 32px rgba(0,0,0,0.24)',
        }),
      }}
    >
      {/* Header */}
      <Box
        sx={{
          p: 2,
          bgcolor: 'background.paper',
          borderBottom: '1px solid rgba(0,0,0,0.08)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexShrink: 0
        }}
      >
        <Stack direction="row" alignItems="center" spacing={1.5}>
          {isSkill ? (
            <PsychologyIcon color="secondary" />
          ) : isSpreadsheet ? (
            <GridOnIcon color="success" />
          ) : (
            <ArticleIcon color="primary" />
          )}
          <Box>
            <Typography variant="body2" sx={{ fontWeight: 700, color: 'text.primary' }}>
              {activeArtifact.title}
            </Typography>
            <Typography variant="caption" color="text.secondary" sx={{ textTransform: 'uppercase', fontSize: 9, letterSpacing: 0.5, fontWeight: 600 }}>
              AI Reference {isSkill ? 'Capability' : isSpreadsheet ? 'Spreadsheet' : 'Document'}
            </Typography>
          </Box>
        </Stack>

        <Stack direction="row" spacing={1} alignItems="center">
          {isSpreadsheet ? (
            <Button
              size="small"
              variant="outlined"
              color="success"
              startIcon={<GridOnIcon />}
              onClick={handleDownloadCSV}
              sx={{ textTransform: 'none', fontSize: 11, py: 0.5 }}
            >
              Export CSV
            </Button>
          ) : (
            <Button
              size="small"
              variant="outlined"
              startIcon={<ContentCopyIcon />}
              onClick={handleCopy}
              sx={{ textTransform: 'none', fontSize: 11, py: 0.5 }}
            >
              {copied ? 'Copied!' : 'Copy'}
            </Button>
          )}

          {isSkill && (
            <>
              <Button
                size="small"
                variant={isSaved ? "outlined" : "contained"}
                color={isSaved ? "success" : "primary"}
                startIcon={isSaved ? <CheckIcon /> : <SaveIcon />}
                onClick={handleSave}
                disabled={isSaved}
                sx={{ textTransform: 'none', fontSize: 11, py: 0.5 }}
              >
                {isSaved ? 'Capability Saved' : 'Save Capability'}
              </Button>
              <Button
                size="small"
                variant="contained"
                color="secondary"
                startIcon={<OpenInNewIcon sx={{ fontSize: 13 }} />}
                onClick={async () => {
                  if (!isSaved) {
                    await handleSave();
                  }
                  setActiveArtifact(activeArtifact); // keeps it active for AgentSkills useEffect
                  navigate('/agent-skills');
                }}
                sx={{ textTransform: 'none', fontSize: 11, py: 0.5 }}
              >
                Open in Editor
              </Button>
            </>
          )}

          <IconButton
            onClick={() => setIsFullscreen(!isFullscreen)}
            size="small"
            sx={{ ml: 0.5 }}
            title={isFullscreen ? "Exit Fullscreen" : "Fullscreen"}
          >
            {isFullscreen ? <FullscreenExitIcon fontSize="small" /> : <FullscreenIcon fontSize="small" />}
          </IconButton>

          <IconButton onClick={() => setActiveArtifact(null)} size="small" sx={{ ml: 0.5 }}>
            <CloseIcon fontSize="small" />
          </IconButton>
        </Stack>
      </Box>

      {/* Content Area */}
      <Box sx={{ flex: 1, p: 3, overflowY: 'auto' }}>
        {isSkill ? (
          <Paper
            variant="outlined"
            sx={(theme) => ({
              p: 3,
              bgcolor: '#18181c',
              color: '#e2e8f0',
              borderColor: 'rgba(0,0,0,0.12)',
              borderRadius: 2,
              fontFamily: 'Consolas, Monaco, "Courier New", monospace',
              fontSize: 12.5,
              lineHeight: 1.6,
              whiteSpace: 'pre-wrap',
              scrollbarWidth: 'thin',
              scrollbarColor: theme.palette.mode === 'dark' ? 'rgba(255,255,255,0.15) transparent' : 'rgba(0,0,0,0.15) transparent',
            })}
          >
            {activeArtifact.content}
          </Paper>
        ) : isSpreadsheet ? (
          <Paper
            variant="outlined"
            sx={{
              p: 0,
              bgcolor: 'background.paper',
              borderRadius: 2,
              borderColor: 'rgba(0,0,0,0.06)',
              boxShadow: '0 2px 12px rgba(0,0,0,0.02)',
              overflowX: 'auto',
              minHeight: '100%',
              display: 'flex',
              flexDirection: 'column',
            }}
          >
            {(() => {
              const data = parseSpreadsheet(activeArtifact.content);
              if (!data) {
                return (
                  <Box sx={{ p: 3, textAlign: 'center' }}>
                    <Typography variant="body2" color="text.secondary" sx={{ fontStyle: 'italic' }}>
                      Invalid or empty spreadsheet format.
                    </Typography>
                  </Box>
                );
              }
              const { headers, rows } = data;
              return (
                <Table size="small" sx={{ borderCollapse: 'collapse', minWidth: 500 }}>
                  <TableHead>
                    {/* Column letters A, B, C */}
                    <TableRow sx={{ bgcolor: '#f4f5f8', height: 26 }}>
                      <TableCell sx={{ width: 40, p: '4px', borderRight: '1px solid #e0e0e0', borderBottom: '1px solid #e0e0e0', bgcolor: '#eaecef' }} />
                      {headers.map((_, i) => (
                        <TableCell
                          key={i}
                          align="center"
                          sx={{
                            p: '4px',
                            fontWeight: 600,
                            fontSize: 10,
                            color: 'text.secondary',
                            borderRight: '1px solid #e0e0e0',
                            borderBottom: '1px solid #e0e0e0',
                            fontFamily: 'monospace, sans-serif',
                            bgcolor: '#eaecef',
                          }}
                        >
                          {String.fromCharCode(65 + i)}
                        </TableCell>
                      ))}
                    </TableRow>
                    {/* Header names row */}
                    <TableRow sx={{ bgcolor: '#fafafa' }}>
                      <TableCell sx={{ bgcolor: '#f4f5f8', width: 40, p: 1, borderRight: '1px solid #e0e0e0', borderBottom: '2px solid #d0d0d0' }} />
                      {headers.map((h, i) => (
                        <TableCell
                          key={i}
                          sx={{
                            p: 1.25,
                            fontWeight: 700,
                            fontSize: 11.5,
                            color: 'text.primary',
                            borderRight: '1px solid #e0e0e0',
                            borderBottom: '2px solid #d0d0d0',
                          }}
                        >
                          {h}
                        </TableCell>
                      ))}
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {rows.map((row, rowIdx) => (
                      <TableRow key={rowIdx} hover>
                        {/* Row index 1, 2, 3 */}
                        <TableCell
                          align="center"
                          sx={{
                            bgcolor: '#f4f5f8',
                            width: 40,
                            p: 1,
                            fontWeight: 600,
                            color: 'text.secondary',
                            fontSize: 11,
                            borderRight: '1px solid #e0e0e0',
                            borderBottom: '1px solid #e0e0e0',
                            userSelect: 'none',
                          }}
                        >
                          {rowIdx + 1}
                        </TableCell>
                        {row.map((cell, cellIdx) => {
                          const cleanCell = cell.trim();
                          const isNum = /^\$?\-?\d+(\.\d+)?%?$/.test(cleanCell.replace(/,/g, ''));
                          const isNegative = cleanCell.startsWith('-') || cleanCell.startsWith('-$');
                          return (
                            <TableCell
                              key={cellIdx}
                              align={isNum ? 'right' : 'left'}
                              sx={{
                                p: 1.25,
                                fontSize: 12,
                                borderRight: '1px solid #e0e0e0',
                                borderBottom: '1px solid #e0e0e0',
                                fontFamily: isNum ? 'monospace, sans-serif' : 'inherit',
                                color: isNegative ? 'error.main' : 'text.primary',
                                fontWeight: isNum ? 500 : 400,
                              }}
                            >
                              {cell}
                            </TableCell>
                          );
                        })}
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              );
            })()}
          </Paper>
        ) : (
          <Paper
            variant="outlined"
            sx={{
              p: 3,
              bgcolor: 'background.paper',
              borderRadius: 2,
              borderColor: 'rgba(0,0,0,0.06)',
              boxShadow: '0 2px 12px rgba(0,0,0,0.02)',
              minHeight: '100%',
            }}
          >
            <SimpleMarkdown content={activeArtifact.content} />
          </Paper>
        )}
      </Box>
    </Box>
  );
}
